services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $extension: '%env(URL_ENV)%'
    App\Orchestrator\Chain\:
        resource: '../../src/Orchestrator/Chain/'
        tags: ['app.orchestrators']
        lazy: true
        shared: true

    App\Orchestrator\OrchestratorChainHandler:
        lazy: true
        shared: true
    App\Orchestrator\OrchestratorChain: '@App\Orchestrator\OrchestratorChainHandler'


    # Multimedia Orchestration
    App\Orchestrator\Chain\MultimediaType\:
        resource: '../../src/Orchestrator/Chain/MultimediaType/'
        tags: [ 'app.multimedia.orchestrators' ]
        lazy: true
        shared: true

    App\Orchestrator\Chain\MultimediaType\MultimediaTypeOrchestratorHandler:
        lazy: true
        shared: true

    App\Orchestrator\Chain\MultimediaType\MultimediaOrchestratorChain: '@App\Orchestrator\Chain\MultimediaType\MultimediaTypeOrchestratorHandler'

    App\Orchestrator\Chain\MultimediaType\MultimediaWidgetOrchestrator:
        tags: [ 'app.multimedia.orchestrators' ]
        arguments:
            $queryWidgetClient: '@Ec\Widget\Domain\Model\QueryWidgetClient'
