services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $extension: '%env(URL_ENV)%'
    App\Orchestrator\Chain\:
        resource: '../../src/Orchestrator/Chain/'
        tags: ['app.orchestrators']
        lazy: true
        shared: true

    App\Orchestrator\OrchestratorChainHandler:
        lazy: true
        shared: true
    App\Orchestrator\OrchestratorChain: '@App\Orchestrator\OrchestratorChainHandler'

    # Multimedia Orchestration
    App\Orchestrator\Chain\Multimedia\:
        resource: '../../src/Orchestrator/Chain/Multimedia/'
        exclude:
            - '../../src/Orchestrator/Chain/Multimedia/MultimediaOrchestratorHandler.php'
            - '../../src/Orchestrator/Chain/Multimedia/MultimediaOrchestratorChain.php'
        tags: [ 'app.multimedia.orchestrators' ]
        lazy: true
        shared: true

    App\Orchestrator\Chain\Multimedia\MultimediaOrchestratorHandler:
        lazy: true
        shared: true

    App\Orchestrator\Chain\Multimedia\MultimediaOrchestratorChain: '@App\Orchestrator\Chain\Multimedia\MultimediaOrchestratorHandler'

    App\Orchestrator\Chain\Multimedia\MultimediaWidgetOrchestrator:
        tags: [ 'app.multimedia.orchestrators' ]
        arguments:
            $queryWidgetClient: '@Ec\Widget\Domain\Model\QueryWidgetClient'
